/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowsIndexRouteImport } from './routes/shows.index'
import { Route as ShowsShowIdIndexRouteImport } from './routes/shows.$showId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIndexRoute = ShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdIndexRoute = ShowsShowIdIndexRouteImport.update({
  id: '/shows/$showId/',
  path: '/shows/$showId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shows/': typeof ShowsIndexRoute
  '/shows/$showId/': typeof ShowsShowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shows': typeof ShowsIndexRoute
  '/shows/$showId': typeof ShowsShowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shows/': typeof ShowsIndexRoute
  '/shows/$showId/': typeof ShowsShowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shows/' | '/shows/$showId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shows' | '/shows/$showId'
  id: '__root__' | '/' | '/shows/' | '/shows/$showId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShowsIndexRoute: typeof ShowsIndexRoute
  ShowsShowIdIndexRoute: typeof ShowsShowIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/': {
      id: '/shows/'
      path: '/shows'
      fullPath: '/shows/'
      preLoaderRoute: typeof ShowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$showId/': {
      id: '/shows/$showId/'
      path: '/shows/$showId'
      fullPath: '/shows/$showId/'
      preLoaderRoute: typeof ShowsShowIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShowsIndexRoute: ShowsIndexRoute,
  ShowsShowIdIndexRoute: ShowsShowIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
