/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountBookingsRouteImport } from './routes/account.bookings'
import { Route as AccountPaymentMethodsRouteImport } from './routes/account.payment-methods'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminShowsRouteImport } from './routes/admin.shows'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as ConfirmationReferenceRouteImport } from './routes/confirmation.$reference'
import { Route as ShowsIndexRouteImport } from './routes/shows.index'
import { Route as VenuesIndexRouteImport } from './routes/venues.index'
import { Route as VenuesVenueIdRouteImport } from './routes/venues.$venueId'
import { Route as AccountTicketsReferenceRouteImport } from './routes/account.tickets.$reference'
import { Route as AdminVenuesIndexRouteImport } from './routes/admin.venues.index'
import { Route as ShowsShowIdIndexRouteImport } from './routes/shows.$showId.index'
import { Route as ShowsShowIdSeatsRouteImport } from './routes/shows.$showId.seats'
import { Route as AdminVenuesVenueIdSeatsRouteImport } from './routes/admin.venues.$venueId.seats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPaymentMethodsRoute = AccountPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShowsRoute = AdminShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationReferenceRoute = ConfirmationReferenceRouteImport.update({
  id: '/confirmation/$reference',
  path: '/confirmation/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIndexRoute = ShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIndexRoute = VenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdRoute = VenuesVenueIdRouteImport.update({
  id: '/venues/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTicketsReferenceRoute = AccountTicketsReferenceRouteImport.update({
  id: '/tickets/$reference',
  path: '/tickets/$reference',
  getParentRoute: () => AccountRoute,
} as any)
const AdminVenuesIndexRoute = AdminVenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => AdminRoute,
} as any)
const ShowsShowIdIndexRoute = ShowsShowIdIndexRouteImport.update({
  id: '/shows/$showId/',
  path: '/shows/$showId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdSeatsRoute = ShowsShowIdSeatsRouteImport.update({
  id: '/shows/$showId/seats',
  path: '/shows/$showId/seats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVenuesVenueIdSeatsRoute = AdminVenuesVenueIdSeatsRouteImport.update({
  id: '/venues/$venueId/seats',
  path: '/venues/$venueId/seats',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/payment-methods': typeof AccountPaymentMethodsRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/shows': typeof AdminShowsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/confirmation/$reference': typeof ConfirmationReferenceRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/shows/': typeof ShowsIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/account/tickets/$reference': typeof AccountTicketsReferenceRoute
  '/shows/$showId/seats': typeof ShowsShowIdSeatsRoute
  '/admin/venues/': typeof AdminVenuesIndexRoute
  '/shows/$showId/': typeof ShowsShowIdIndexRoute
  '/admin/venues/$venueId/seats': typeof AdminVenuesVenueIdSeatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/payment-methods': typeof AccountPaymentMethodsRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/shows': typeof AdminShowsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/confirmation/$reference': typeof ConfirmationReferenceRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/shows': typeof ShowsIndexRoute
  '/venues': typeof VenuesIndexRoute
  '/account/tickets/$reference': typeof AccountTicketsReferenceRoute
  '/shows/$showId/seats': typeof ShowsShowIdSeatsRoute
  '/admin/venues': typeof AdminVenuesIndexRoute
  '/shows/$showId': typeof ShowsShowIdIndexRoute
  '/admin/venues/$venueId/seats': typeof AdminVenuesVenueIdSeatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/payment-methods': typeof AccountPaymentMethodsRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/shows': typeof AdminShowsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/confirmation/$reference': typeof ConfirmationReferenceRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/shows/': typeof ShowsIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/account/tickets/$reference': typeof AccountTicketsReferenceRoute
  '/shows/$showId/seats': typeof ShowsShowIdSeatsRoute
  '/admin/venues/': typeof AdminVenuesIndexRoute
  '/shows/$showId/': typeof ShowsShowIdIndexRoute
  '/admin/venues/$venueId/seats': typeof AdminVenuesVenueIdSeatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/account/bookings'
    | '/account/payment-methods'
    | '/account/profile'
    | '/admin/roles'
    | '/admin/shows'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/confirmation/$reference'
    | '/venues/$venueId'
    | '/account/'
    | '/admin/'
    | '/shows/'
    | '/venues/'
    | '/account/tickets/$reference'
    | '/shows/$showId/seats'
    | '/admin/venues/'
    | '/shows/$showId/'
    | '/admin/venues/$venueId/seats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/account/bookings'
    | '/account/payment-methods'
    | '/account/profile'
    | '/admin/roles'
    | '/admin/shows'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/confirmation/$reference'
    | '/venues/$venueId'
    | '/account'
    | '/admin'
    | '/shows'
    | '/venues'
    | '/account/tickets/$reference'
    | '/shows/$showId/seats'
    | '/admin/venues'
    | '/shows/$showId'
    | '/admin/venues/$venueId/seats'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/account/bookings'
    | '/account/payment-methods'
    | '/account/profile'
    | '/admin/roles'
    | '/admin/shows'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/confirmation/$reference'
    | '/venues/$venueId'
    | '/account/'
    | '/admin/'
    | '/shows/'
    | '/venues/'
    | '/account/tickets/$reference'
    | '/shows/$showId/seats'
    | '/admin/venues/'
    | '/shows/$showId/'
    | '/admin/venues/$venueId/seats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ConfirmationReferenceRoute: typeof ConfirmationReferenceRoute
  VenuesVenueIdRoute: typeof VenuesVenueIdRoute
  ShowsIndexRoute: typeof ShowsIndexRoute
  VenuesIndexRoute: typeof VenuesIndexRoute
  ShowsShowIdSeatsRoute: typeof ShowsShowIdSeatsRoute
  ShowsShowIdIndexRoute: typeof ShowsShowIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/bookings': {
      id: '/account/bookings'
      path: '/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/payment-methods': {
      id: '/account/payment-methods'
      path: '/payment-methods'
      fullPath: '/account/payment-methods'
      preLoaderRoute: typeof AccountPaymentMethodsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shows': {
      id: '/admin/shows'
      path: '/shows'
      fullPath: '/admin/shows'
      preLoaderRoute: typeof AdminShowsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$reference': {
      id: '/confirmation/$reference'
      path: '/confirmation/$reference'
      fullPath: '/confirmation/$reference'
      preLoaderRoute: typeof ConfirmationReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/': {
      id: '/shows/'
      path: '/shows'
      fullPath: '/shows/'
      preLoaderRoute: typeof ShowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/': {
      id: '/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof VenuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venueId': {
      id: '/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof VenuesVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/tickets/$reference': {
      id: '/account/tickets/$reference'
      path: '/tickets/$reference'
      fullPath: '/account/tickets/$reference'
      preLoaderRoute: typeof AccountTicketsReferenceRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/venues/': {
      id: '/admin/venues/'
      path: '/venues'
      fullPath: '/admin/venues/'
      preLoaderRoute: typeof AdminVenuesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shows/$showId/': {
      id: '/shows/$showId/'
      path: '/shows/$showId'
      fullPath: '/shows/$showId/'
      preLoaderRoute: typeof ShowsShowIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$showId/seats': {
      id: '/shows/$showId/seats'
      path: '/shows/$showId/seats'
      fullPath: '/shows/$showId/seats'
      preLoaderRoute: typeof ShowsShowIdSeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/venues/$venueId/seats': {
      id: '/admin/venues/$venueId/seats'
      path: '/venues/$venueId/seats'
      fullPath: '/admin/venues/$venueId/seats'
      preLoaderRoute: typeof AdminVenuesVenueIdSeatsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AccountRouteChildren {
  AccountBookingsRoute: typeof AccountBookingsRoute
  AccountPaymentMethodsRoute: typeof AccountPaymentMethodsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountTicketsReferenceRoute: typeof AccountTicketsReferenceRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountBookingsRoute: AccountBookingsRoute,
  AccountPaymentMethodsRoute: AccountPaymentMethodsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountTicketsReferenceRoute: AccountTicketsReferenceRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminRolesRoute: typeof AdminRolesRoute
  AdminShowsRoute: typeof AdminShowsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminVenuesIndexRoute: typeof AdminVenuesIndexRoute
  AdminVenuesVenueIdSeatsRoute: typeof AdminVenuesVenueIdSeatsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRolesRoute: AdminRolesRoute,
  AdminShowsRoute: AdminShowsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminVenuesIndexRoute: AdminVenuesIndexRoute,
  AdminVenuesVenueIdSeatsRoute: AdminVenuesVenueIdSeatsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ConfirmationReferenceRoute: ConfirmationReferenceRoute,
  VenuesVenueIdRoute: VenuesVenueIdRoute,
  ShowsIndexRoute: ShowsIndexRoute,
  VenuesIndexRoute: VenuesIndexRoute,
  ShowsShowIdSeatsRoute: ShowsShowIdSeatsRoute,
  ShowsShowIdIndexRoute: ShowsShowIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
